services:
  - type: web
    name: portfolio-backend
    region: oregon
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: ${MONGODB_URI}
      - key: ADMIN_USERNAME
        value: ${ADMIN_USERNAME}
      - key: ADMIN_PASSWORD
        value: ${ADMIN_PASSWORD}
      - key: FRONTEND_URL
        value: ${FRONTEND_URL}
    envVarGroups:
      - fromGroup: portfolio-prod
        optional: true